[apply_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh --action reload
parameters:
type:script_output
message:apply app identification custom rules by reloading ntopng

[ntopng_generate]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh
parameters:%s %s %s %s %s %s %s %s %s %s
type:script_output
message:generate /usr/local/etc/ntopng/ntopng.conf

[ntopng_restart]
command:/usr/local/etc/rc.d/ntopng restart
parameters:
type:script
message:Restart ntopng

[read_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh --action read_rules
parameters:
type:script_output
message:Read ntopng custom application rules

[write_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh --action write_rules
parameters:%s
type:script_output
message:Write ntopng custom application rules

[reload]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh --action reload
parameters:
type:script_output
message:Reload ntopng for custom rules

[status]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh --action status
parameters:
type:script_output
message:Get ntopng process status
