[apply_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php reload
parameters:
type:script_output
message:apply app identification custom rules by reloading ntopng

[ntopng_generate]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php --legacy-generate
parameters:%s %s %s %s %s %s %s %s %s %s
type:script_output
message:generate /usr/local/etc/ntopng/ntopng.conf

[ntopng_restart]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php restart
parameters:
type:script
message:Restart ntopng

[start]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php start
parameters:
type:script_output
message:Start App Identification services

[stop]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php stop
parameters:
type:script_output
message:Stop App Identification services

[read_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php read_rules
parameters:
type:script_output
message:Read ntopng custom application rules

[write_rules]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php --legacy-write
parameters:%s
type:script_output
message:Write ntopng custom application rules

[reload]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php reload
parameters:
type:script_output
message:Reload ntopng for custom rules

[status]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php status
parameters:
type:script_output
message:Get ntopng process status

[backend]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/backend.php --request
parameters:%s
type:script_output
message:App Identification backend adapter
