[apply_rules]
command:/usr/local/etc/rc.d/ntopng restart
parameters:
type:script_output
message:apply app identification custom rules by restarting ntopng

[ntopng_generate]
command:/usr/local/opnsense/scripts/OPNsense/AppIdentification/ntopng_api_proxy.sh
parameters:%s %s %s %s %s %s %s %s %s %s
type:script_output
message:generate /usr/local/etc/ntopng/ntopng.conf

[ntopng_restart]
command:/usr/local/etc/rc.d/ntopng restart
parameters:
type:script
message:Restart ntopng
