<script>
    $(document).ready(function () {
        $('#records').UIBootgrid({
            search: '/api/antivirus/logs/search',
            options: {
                rowCount: [-1, 10, 25, 50, 100]
            }
        });
    });
</script>

<div class="content-box">
    <div class="alert alert-info" style="margin-top: 10px;">
        {{ lang._('Events are generated by sidecar workers and include SHA256, verdict, signature and source IP.') }}
    </div>
    <table id="records" class="table table-condensed table-hover table-striped table-responsive" data-editDialog="DialogRecord">
        <thead>
            <tr>
                <th data-column-id="timestamp">{{ lang._('Time') }}</th>
                <th data-column-id="sha256">SHA256</th>
                <th data-column-id="result">{{ lang._('Result') }}</th>
                <th data-column-id="signature">{{ lang._('Signature') }}</th>
                <th data-column-id="source_ip">{{ lang._('Source IP') }}</th>
                <th data-column-id="file_path">{{ lang._('File') }}</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>