PLUGIN_NAME=        app-identification
PLUGIN_VERSION=     1.0
PLUGIN_REVISION=    1
PLUGIN_COMMENT=     Application identification dashboard backed by ntopng
PLUGIN_DEPENDS=     ntopng redis72

.include "../../Mk/plugins.mk"
