[start]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php start
parameters:
type:script
message:starting antivirus

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php stop
parameters:
type:script
message:stopping antivirus

[reload]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php reload
parameters:
type:script
message:reloading antivirus config

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php restart
parameters:
type:script
message:restarting antivirus

[status]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php status
parameters:
type:script_output
message:query antivirus status

[start_service]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php start_service
parameters:%s
type:script_output
message:starting antivirus component

[freshclam]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php freshclam
parameters:%s
type:script_output
message:Check or install signatures

[version]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php version
parameters:
type:script_output
message:Get ClamAV and signature versions

[logs]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/backend.php logs
parameters:%s
type:script_output
message:Get Antivirus logs
