[start]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/start.sh
parameters:
type:script
message:starting antivirus stack

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/stop.sh
parameters:
type:script
message:stopping antivirus stack

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/stop.sh && /usr/local/opnsense/scripts/OPNsense/Antivirus/start.sh
parameters:
type:script
message:restarting antivirus stack

[reload]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/reload.sh
parameters:
type:script
message:reloading antivirus config

[status]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/status.sh
parameters:
type:script_output
message:query antivirus status

[update_sigs]
command:/usr/local/sbin/freshclam --no-warnings
parameters:
type:script_output
message:updating ClamAV signatures
