[start]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py start
parameters:
type:script_output
message:starting Antivirus

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py stop
parameters:
type:script_output
message:stopping Antivirus

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py restart
parameters:
type:script_output
message:restarting Antivirus

[reload]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py reload
parameters:
type:script_output
message:reloading Antivirus

[status]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py status
parameters:
type:script_output
message:request Antivirus status

[apply]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py apply
parameters:
type:script_output
message:apply Antivirus configuration

[repair]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py repair
parameters:
type:script_output
message:repair Antivirus configuration

[eicar_test]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py eicar_test
parameters:
type:script_output
message:run Antivirus EICAR test

[update_db]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py update_db
parameters:
type:script_output
message:update Antivirus signatures

[parse_logs]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py parse_logs
parameters:
type:script_output
message:parse Antivirus logs

[dashboard]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py dashboard
parameters:
type:script_output
message:get Antivirus dashboard

[logs]
command:/usr/local/opnsense/scripts/OPNsense/Antivirus/antivirusctl.py logs
parameters:
type:script_output
message:get Antivirus logs
