PLUGIN_NAME=		anti-virus
PLUGIN_VERSION=		1.0.0
PLUGIN_COMMENT=		Integrated Antivirus proxy (c-icap + ClamAV)
PLUGIN_DEPENDS=		squid squid-langpack clamav c-icap c-icap-modules
PLUGIN_MAINTAINER=	xwy@example.com

.include "../../Mk/plugins.mk"
