PLUGIN_NAME=        anti-virus
PLUGIN_VERSION=     1.0
PLUGIN_COMMENT=     Industrial bypass antivirus chain (extract-scan-block)
PLUGIN_DEPENDS=     clamav python311 py311-watchdog
PLUGIN_MAINTAINER=  xwy@example.com

.include "../../Mk/plugins.mk"