[reload]
command:/usr/local/opnsense/scripts/indproto/generate_rules.py
parameters:
type:script_output
message:generate industrial protocol Suricata rules

[restart_suricata]
command:/usr/local/sbin/pluginctl -s suricata restart
parameters:
type:script
message:restart Suricata

[log]
command:/usr/local/opnsense/scripts/indproto/log_query.py
parameters:--proto %s --src_ip %s --dst_ip %s --start_time %s --end_time %s --limit %s
type:script_output
message:querying indproto logs
