[reload]
command:/usr/local/opnsense/scripts/indproto/backend.py reload
parameters:
type:script_output
message:generate industrial protocol Suricata rules

[restart_suricata]
command:/usr/local/opnsense/scripts/indproto/backend.py restart_suricata
parameters:
type:script
message:restart Suricata

[log]
command:/usr/local/opnsense/scripts/indproto/backend.py log
parameters:--proto %s --src_ip %s --dst_ip %s --start_time %s --end_time %s --limit %s
type:script_output
message:querying indproto logs
