[reload]
command:/usr/local/opnsense/scripts/indproto/backend.py reload
parameters:
type:script_output
message:generate industrial protocol Suricata rules

[configure]
command:/usr/local/opnsense/scripts/indproto/backend.py configure
parameters:
type:script_output
message:generate Suricata configuration for industrial protocol inspection

[start]
command:/usr/local/opnsense/scripts/indproto/backend.py start
parameters:
type:script_output
message:start Suricata for industrial protocol inspection

[stop]
command:/usr/local/opnsense/scripts/indproto/backend.py stop
parameters:
type:script_output
message:stop Suricata for industrial protocol inspection

[restart_suricata]
command:/usr/local/opnsense/scripts/indproto/backend.py restart_suricata
parameters:
type:script
message:restart Suricata

[log]
command:/usr/local/opnsense/scripts/indproto/backend.py log
parameters:--proto %s --src_ip %s --dst_ip %s --start_time %s --end_time %s --limit %s
type:script_output
message:querying indproto logs
