[generate]
command:/usr/local/opnsense/scripts/OPNsense/IndustrialWhitelist/generate_suricata_rules.py
parameters:
type:script_output
message:generate industrial whitelist suricata rules

[flush_states]
command:/usr/local/opnsense/scripts/OPNsense/IndustrialWhitelist/flush_states.sh
parameters:
type:script_output
message:flush industrial whitelist managed states
