#!/bin/sh
#
# PROVIDE: antivirus_logparser
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="antivirus_logparser"
rcvar="antivirus_logparser_enable"

command="/usr/local/opnsense/scripts/OPNsense/Antivirus/log_parser.py"
pidfile="/var/run/antivirus_logparser.pid"
start_cmd="antivirus_logparser_start"
stop_cmd="antivirus_logparser_stop"
status_cmd="antivirus_logparser_status"

load_rc_config ${name}

: "${antivirus_logparser_enable="NO"}"

antivirus_logparser_start()
{
    if pgrep -qF "${pidfile}" 2>/dev/null; then
        echo "${name} is already running."
        return 0
    fi

    echo "starting ${name}"
    daemon -f -p "${pidfile}" "${command}"
}

antivirus_logparser_stop()
{
    if pgrep -qF "${pidfile}" 2>/dev/null; then
        echo "stopping ${name}"
        pkill -F "${pidfile}" 2>/dev/null || :
        rm -f "${pidfile}"
    else
        echo "${name} is not running."
    fi
}

antivirus_logparser_status()
{
    if pgrep -qF "${pidfile}" 2>/dev/null; then
        echo "${name} is running."
        return 0
    fi

    echo "${name} is not running."
    return 1
}

run_rc_command "$1"
