#!/bin/sh

set -eu

TARGET_DIR="/usr/local/etc/ntopng"
TARGET_FILE="${TARGET_DIR}/ntopng.conf"

ENABLED="${1:-0}"
INTERFACES="${2:-}"
HTTP_PORT="${3:-3000}"
HTTPS_PORT="${4:-}"
DNS_MODE="${5:-0}"
CERTIFICATE="${6:-}"
MAX_FLOWS="${7:-200000}"
MAX_HOSTS="${8:-100000}"
LOCAL_NETWORKS="${9:-}"
EXTRA_OPTIONS="${10:-}"

mkdir -p "${TARGET_DIR}"

{
	echo "# Autogenerated by os-app-identification"
	echo "# Do not edit manually"
	echo ""

	if [ "${ENABLED}" = "1" ]; then
		echo "-e="
	fi

	if [ -n "${INTERFACES}" ]; then
		IFS=','
		for iface in ${INTERFACES}; do
			iface_trimmed=$(echo "${iface}" | xargs)
			[ -n "${iface_trimmed}" ] && echo "-i=${iface_trimmed}"
		done
		unset IFS
	fi

	echo "--http-port=${HTTP_PORT}"
	[ -n "${HTTPS_PORT}" ] && echo "--https-port=${HTTPS_PORT}"
	echo "--dns-mode=${DNS_MODE}"
	[ -n "${CERTIFICATE}" ] && echo "--https-cert=${CERTIFICATE}"
	[ -n "${MAX_FLOWS}" ] && echo "--max-num-flows=${MAX_FLOWS}"
	[ -n "${MAX_HOSTS}" ] && echo "--max-num-hosts=${MAX_HOSTS}"
	[ -n "${LOCAL_NETWORKS}" ] && echo "--local-networks=${LOCAL_NETWORKS}"

	if [ -n "${EXTRA_OPTIONS}" ]; then
		printf "%s\n" "${EXTRA_OPTIONS}" | tr ';' '\n'
	fi
} > "${TARGET_FILE}"

echo "Generated ${TARGET_FILE}"
