#!/bin/sh

set -u

TARGET_DIR="/usr/local/etc/ntopng"
TARGET_FILE="${TARGET_DIR}/ntopng.conf"
RULES_FILE="/var/lib/ntopng/protos.txt"
RULES_BAK="${RULES_FILE}.bak"
RULES_LOCK_FILE="/var/run/appidentification_rules.lock"
PHP_BIN="$(command -v php || true)"

json_escape()
{
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e ':a;N;$!ba;s/\n/\\n/g'
}

json_ok()
{
	printf '{"status":"ok","data":%s}\n' "$1"
}

json_error()
{
	msg="$(json_escape "$1")"
	printf '{"status":"error","message":"%s"}\n' "${msg}"
	exit 1
}

require_php()
{
	[ -n "${PHP_BIN}" ] || json_error "php binary not found"
}

generate_config()
{
	ENABLED="${1:-0}"
	INTERFACES="${2:-}"
	HTTP_PORT="${3:-3000}"
	HTTPS_PORT="${4:-}"
	DNS_MODE="${5:-0}"
	CERTIFICATE="${6:-}"
	MAX_FLOWS="${7:-200000}"
	MAX_HOSTS="${8:-100000}"
	LOCAL_NETWORKS="${9:-}"
	EXTRA_OPTIONS="${10:-}"

	if ! mkdir -p "${TARGET_DIR}"; then
		json_error "failed to create ${TARGET_DIR}"
	fi

	if ! {
		echo "# Autogenerated by os-app-identification"
		echo "# Do not edit manually"
		echo ""

		if [ "${ENABLED}" = "1" ]; then
			echo "-e="
		fi

		if [ -n "${INTERFACES}" ]; then
			IFS=','
			for iface in ${INTERFACES}; do
				iface_trimmed=$(echo "${iface}" | xargs)
				[ -n "${iface_trimmed}" ] && echo "-i=${iface_trimmed}"
			done
			unset IFS
		fi

		echo "--http-port=${HTTP_PORT}"
		[ -n "${HTTPS_PORT}" ] && echo "--https-port=${HTTPS_PORT}"
		echo "--dns-mode=${DNS_MODE}"
		[ -n "${CERTIFICATE}" ] && echo "--https-cert=${CERTIFICATE}"
		[ -n "${MAX_FLOWS}" ] && echo "--max-num-flows=${MAX_FLOWS}"
		[ -n "${MAX_HOSTS}" ] && echo "--max-num-hosts=${MAX_HOSTS}"
		[ -n "${LOCAL_NETWORKS}" ] && echo "--local-networks=${LOCAL_NETWORKS}"

		if [ -n "${EXTRA_OPTIONS}" ]; then
			printf "%s\\n" "${EXTRA_OPTIONS}" | tr ';' '\n'
		fi
	} > "${TARGET_FILE}"; then
		json_error "failed to write ${TARGET_FILE}"
	fi

	json_ok "{\"generated\":\"${TARGET_FILE}\"}"
}

read_rules()
{
	require_php
	"${PHP_BIN}" -r '
		$file = $argv[1];
		$rules = [];
		if (is_file($file)) {
			foreach (file($file, FILE_IGNORE_NEW_LINES) as $line) {
				$line = rtrim($line, "\\r\\n");
				if ($line === "") {
					continue;
				}
				$rules[] = $line;
			}
		}
		echo json_encode(["status" => "ok", "data" => $rules], JSON_UNESCAPED_SLASHES) . PHP_EOL;
	' "${RULES_FILE}" || json_error "failed to read ${RULES_FILE}"
}

write_rules()
{
	require_php
	command -v flock >/dev/null 2>&1 || json_error "flock utility not found"
	mkdir -p /var/run || json_error "failed to create /var/run"
	: > "${RULES_LOCK_FILE}" || json_error "failed to prepare lock file"
	exec 9>"${RULES_LOCK_FILE}" || json_error "failed to open lock file"
	if ! flock -x 9; then
		json_error "failed to acquire rules write lock"
	fi

	payload="${1:-}"
	if [ -z "${payload}" ]; then
		payload="$(cat)"
	fi
	[ -n "${payload}" ] || json_error "empty JSON payload"

	dirname="$(dirname "${RULES_FILE}")"
	if ! mkdir -p "${dirname}"; then
		json_error "failed to create ${dirname}"
	fi

	tmpfile="$(mktemp "${RULES_FILE}.tmp.XXXXXX")" || json_error "failed to create temp file"
	trap 'rm -f "${tmpfile}"; flock -u 9 2>/dev/null || true; exec 9>&- 2>/dev/null || true' EXIT INT TERM HUP

	count=$("${PHP_BIN}" -r '
		$input = $argv[1];
		$tmp = $argv[2];
		$data = json_decode($input, true);
		if (json_last_error() !== JSON_ERROR_NONE) {
			fwrite(STDERR, "invalid JSON payload");
			exit(2);
		}
		if (is_array($data) && array_keys($data) === range(0, count($data) - 1)) {
			$rules = $data;
		} elseif (is_array($data) && isset($data["data"]) && is_array($data["data"])) {
			$rules = $data["data"];
		} elseif (is_array($data) && isset($data["rules"]) && is_array($data["rules"])) {
			$rules = $data["rules"];
		} else {
			fwrite(STDERR, "unsupported payload format");
			exit(3);
		}

		$out = [];
		foreach ($rules as $rule) {
			if (!is_scalar($rule) && $rule !== null) {
				fwrite(STDERR, "rules must be scalar values");
				exit(4);
			}
			$line = trim((string)$rule);
			if ($line === "") {
				continue;
			}
			$out[] = $line;
		}

		$content = implode(PHP_EOL, $out);
		if ($content !== "") {
			$content .= PHP_EOL;
		}

		if (file_put_contents($tmp, $content) === false) {
			fwrite(STDERR, "failed to write temp rules file");
			exit(5);
		}

		echo count($out);
	' "${payload}" "${tmpfile}") || json_error "failed to parse or stage rules"

	if [ -f "${RULES_FILE}" ] && ! cp -p "${RULES_FILE}" "${RULES_BAK}"; then
		json_error "failed to backup ${RULES_FILE}"
	fi

	if ! mv "${tmpfile}" "${RULES_FILE}"; then
		json_error "failed to move staged rules into place"
	fi

	if ! chown ntopng:ntopng "${RULES_FILE}"; then
		json_error "failed to set owner ntopng:ntopng on ${RULES_FILE}"
	fi

	if ! chmod 640 "${RULES_FILE}"; then
		json_error "failed to set permissions on ${RULES_FILE}"
	fi

	trap - EXIT INT TERM HUP
	flock -u 9 2>/dev/null || true
	exec 9>&-
	json_ok "{\"written\":${count},\"file\":\"${RULES_FILE}\",\"backup\":\"${RULES_BAK}\"}"
}

reload_ntopng()
{
	if pgrep -x ntopng >/dev/null 2>&1 && pkill -HUP -x ntopng >/dev/null 2>&1; then
		json_ok '{"method":"sighup"}'
		return
	fi

	if /usr/local/etc/rc.d/ntopng restart >/dev/null 2>&1; then
		json_ok '{"method":"restart"}'
		return
	fi

	json_error "failed to reload ntopng"
}

status_ntopng()
{
	require_php
	pids_raw="$(pgrep -x ntopng 2>/dev/null | tr '\n' ' ' | xargs 2>/dev/null || true)"
	"${PHP_BIN}" -r '
		$raw = trim($argv[1]);
		$pids = [];
		if ($raw !== "") {
			foreach (preg_split("/\\s+/", $raw) as $pid) {
				if ($pid !== "") {
					$pids[] = (int)$pid;
				}
			}
		}
		echo json_encode([
			"status" => "ok",
			"data" => [
				"running" => count($pids) > 0,
				"pids" => $pids,
			],
		], JSON_UNESCAPED_SLASHES) . PHP_EOL;
	' "${pids_raw}" || json_error "failed to build status payload"
}

dispatch_action()
{
	action="${1:-}"
	case "${action}" in
	read_rules)
		read_rules
		;;
	write_rules)
		write_rules "${2:-}"
		;;
	reload)
		reload_ntopng
		;;
	status)
		status_ntopng
		;;
	*)
		json_error "unsupported action: ${action}"
		;;
	esac
}

if [ "${1:-}" = "--action" ]; then
	dispatch_action "${2:-}" "${3:-}"
	exit 0
fi

# Backward-compatible mode for ntopng.conf generation called by configd.
generate_config "$@"
