PLUGIN_NAME=		icsguard
PLUGIN_VERSION=		0.1.0
PLUGIN_COMMENT=		Industrial protocol whitelist rules for Suricata
PLUGIN_DEPENDS=		suricata
PLUGIN_MAINTAINER=	xwy@example.com

.include "../../Mk/plugins.mk"
