# logfilename                    [owner:group]    mode    count   size    when    flags   [/pid_file]                 [sig_num]
/var/log/ndpi_audit.log         root:wheel       640     7       1024    *       ZN
/var/log/ndpi_audit.err         root:wheel       640     7       512     *       ZN
