PidFile /var/run/c-icap/c-icap.pid
CommandsSocket /var/run/c-icap/c-icap.ctl
ServerLog /var/log/c-icap/server.log
AccessLog /var/log/c-icap/access.log
ServerAdmin root@localhost
ServerName {{ system.hostname }}
TmpDir /var/tmp
MaxMemObject 131072
DebugLevel 1
Pipelining on
SupportBuggyClients off
ModulesDir /usr/local/lib/c_icap
ServicesDir /usr/local/lib/c_icap
TemplateDir /tmp/c-icap/templates/
TemplateDefaultLanguage en
LoadMagicFile /usr/local/etc/c-icap/c-icap.magic

Port 127.0.0.1:1344
StartServers 3
MaxServers 10
MinSpareThreads 10
MaxSpareThreads 20
ThreadsPerChild 10
MaxRequestsPerChild 0

Module logger sys_logger.so
Logger sys_logger
sys_logger.Prefix "antivirus-c-icap"

Service antivirus_module virus_scan.so
ServiceAlias srv_clamav virus_scan
ServiceAlias avscan virus_scan?allow204=on&force=on&sizelimit=off&mode=simple
virus_scan.DefaultEngine clamd
virus_scan.ScanFileTypes TEXT DATA EXECUTABLE ARCHIVE GIF JPEG MSOFFICE
virus_scan.Allow204Responces on
virus_scan.PassOnError on
{% if helpers.exists('OPNsense.antivirus.general.max_scan_size') and OPNsense.antivirus.general.max_scan_size != '' %}
virus_scan.MaxObjectSize {{ OPNsense.antivirus.general.max_scan_size }}
{% endif %}
Module common clamd_mod.so
clamd_mod.ClamdHost 127.0.0.1
clamd_mod.ClamdPort 3310
