ServerPort 1344
TmpDir /tmp
MaxMemObject 4096
Module common clamd_mod.so
clamd_mod.ClamdSocket /var/run/clamav/clamd.sock
Service antivirus virus_scan.so
virus_scan.ScanFileTypes TEXT DATA EXECUTABLE ARCHIVE GIF JPEG MSOFFICE
virus_scan.Allow204Responces on
virus_scan.PassOnError on
{% if helpers.exists('OPNsense.antivirus.general.max_scan_size') and OPNsense.antivirus.general.max_scan_size != '' %}
virus_scan.MaxObjectSize {{ OPNsense.antivirus.general.max_scan_size }}
{% endif %}
