LogTime yes
LogSyslog yes
PidFile /var/run/clamav/clamd.pid
DatabaseDirectory /var/db/clamav
LocalSocket /var/run/clamav/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 127.0.0.1
User clamav
{% if helpers.exists('OPNsense.antivirus.general.scan_options') and OPNsense.antivirus.general.scan_options != '' %}
{%   set scan_options = OPNsense.antivirus.general.scan_options.split(',') %}
{% else %}
{%   set scan_options = 'pe,elf,ole2,pdf,swf,xmldocs,hwp3,mail,html,archive'.split(',') %}
{% endif %}
{% if 'pe' in scan_options %}
ScanPE yes
{% endif %}
{% if 'elf' in scan_options %}
ScanELF yes
{% endif %}
{% if 'broken' in scan_options %}
AlertBrokenExecutables yes
{% endif %}
{% if 'ole2' in scan_options %}
ScanOLE2 yes
{% endif %}
{% if 'pdf' in scan_options %}
ScanPDF yes
{% endif %}
{% if 'swf' in scan_options %}
ScanSWF yes
{% endif %}
{% if 'xmldocs' in scan_options %}
ScanXMLDOCS yes
{% endif %}
{% if 'hwp3' in scan_options %}
ScanHWP3 yes
{% endif %}
{% if 'mail' in scan_options %}
ScanMail yes
{% endif %}
{% if 'html' in scan_options %}
ScanHTML yes
{% endif %}
{% if 'archive' in scan_options %}
ScanArchive yes
{% endif %}
{% if 'encrypted_archive' in scan_options %}
AlertEncryptedArchive yes
{% endif %}
{% if helpers.exists('OPNsense.antivirus.general.max_scan_size') and OPNsense.antivirus.general.max_scan_size != '' %}
MaxScanSize {{ OPNsense.antivirus.general.max_scan_size }}
{% endif %}
{% if helpers.exists('OPNsense.antivirus.general.max_file_size') and OPNsense.antivirus.general.max_file_size != '' %}
MaxFileSize {{ OPNsense.antivirus.general.max_file_size }}
{% endif %}
