DatabaseDirectory /var/db/clamav
LogSyslog yes
LogTime yes
PidFile /var/run/clamav/freshclam.pid
DatabaseOwner clamav
NotifyClamd /usr/local/etc/clamd.conf
DatabaseMirror database.clamav.net
ConnectTimeout 60
