DatabaseDirectory /var/db/clamav
LogSyslog yes
LogTime yes
PidFile /var/run/clamav/freshclam.pid
DatabaseOwner clamav
NotifyClamd /usr/local/etc/clamd.conf
{% if helpers.exists('OPNsense.antivirus.url.lists.list') %}
{%   for sig_list in helpers.toList('OPNsense.antivirus.url.lists.list') %}
{%     if sig_list.enabled == '1' %}
DatabaseCustomURL {{ sig_list.link }}
{%     endif %}
{%   endfor %}
{% endif %}
DatabaseMirror database.clamav.net
ConnectTimeout 60
