DatabaseDirectory /var/db/clamav
DatabaseOwner clamav
LogTime yes
LogSyslog yes
UpdateLogFile /var/log/clamav/freshclam.log
PidFile /var/run/clamav/freshclam.pid
DatabaseMirror database.clamav.net
NotifyClamd /usr/local/etc/clamd.conf

{% set interval = OPNsense.antivirus.general.freshclam_interval|default('4')|int %}
{% if interval > 0 %}
Checks {{ (24 / interval)|int }}
{% else %}
Checks 6
{% endif %}
