Module common clamd_mod.so
clamd_mod.ClamdHost 127.0.0.1
clamd_mod.ClamdPort 3310

Service antivirus_module virus_scan.so
virus_scan.ScanFileTypes TEXT DATA EXECUTABLE ARCHIVE GIF JPEG MSOFFICE
virus_scan.Allow204Responces on
virus_scan.PassOnError on
virus_scan.MaxObjectSize 5M
