#!/usr/local/bin/python3

import json
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import generate_rules
import log_query

CONFIG_XML = Path("/conf/config.xml")
SURICATA_RC = Path("/etc/rc.conf.d/suricata")
SURICATA_DIR = Path("/usr/local/etc/suricata")
SURICATA_LOG_DIR = Path("/var/log/suricata")


class CapabilityProbe:
    def probe(self):
        available = {
            "suricata_binary": shutil.which("suricata") is not None or Path("/usr/local/bin/suricata").exists(),
            "suricata_rc": Path("/usr/local/etc/rc.d/suricata").exists(),
            "configctl": shutil.which("configctl") is not None or Path("/usr/local/sbin/configctl").exists(),
            "rules_dir_writable": self.dir_writable(generate_rules.RULES_PATH.parent),
            "suricata_yaml": generate_rules.SURICATA_YAML.exists(),
            "suricata_config_dir_writable": self.dir_writable(SURICATA_DIR),
            "suricata_rc_writable": self.file_writable(SURICATA_RC),
        }
        return {
            "available": available,
            "missing": [name for name, ok in available.items() if not ok],
        }

    def dir_writable(self, path):
        path = Path(path)
        if path.exists():
            return os.access(path, os.W_OK)
        return os.access(path.parent, os.W_OK)

    def file_writable(self, path):
        path = Path(path)
        if path.exists():
            return os.access(path, os.W_OK)
        return os.access(path.parent, os.W_OK)


class ConflictDetector:
    def detect(self):
        conflicts = []
        if self.pkg_installed("os-intrusion-detection-content-et-open"):
            conflicts.append({
                "type": "plugin",
                "name": "os-intrusion-detection-content-et-open",
                "message": "additional Suricata rule content plugin detected",
            })
        return conflicts

    def pkg_installed(self, name):
        return subprocess.run(["/usr/local/sbin/pkg", "info", "-e", name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


class ConfigManager:
    def apply(self):
        config = self.load_indproto_config()
        general = config.find("general")
        enabled = self.text(general, "enabled", "0") in ("1", "true", "yes", "on") if general is not None else False
        logical_iface = self.text(general, "interface", "") if general is not None else ""
        physical_iface = self.physical_interface(logical_iface)

        self.prepare_runtime()
        self.write_suricata_yaml(physical_iface)
        self.write_rc(enabled, physical_iface)
        return ok({
            "data": {
                "enabled": enabled,
                "interface": logical_iface,
                "physical_interface": physical_iface,
                "yaml": str(generate_rules.SURICATA_YAML),
                "rc": str(SURICATA_RC),
            }
        }, "Suricata configuration generated")

    def prepare_runtime(self):
        for path in [SURICATA_DIR, generate_rules.RULES_PATH.parent, SURICATA_LOG_DIR]:
            path.mkdir(parents=True, exist_ok=True)

    def write_suricata_yaml(self, interface):
        iface = interface or "lo0"
        content = f"""# Autogenerated by os-icsguard
%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[any]"
    EXTERNAL_NET: "any"
default-log-dir: /var/log/suricata
rule-files:
  - opnsense.rules/indproto.rules
outputs:
  - fast:
      enabled: yes
      filename: fast.log
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert
        - flow
af-packet:
  - interface: {iface}
    cluster-id: 98
    cluster-type: cluster_flow
    defrag: yes
pcap:
  - interface: {iface}
app-layer:
  protocols:
    modbus:
      enabled: yes
    dnp3:
      enabled: yes
"""
        generate_rules.SURICATA_YAML.parent.mkdir(parents=True, exist_ok=True)
        generate_rules.SURICATA_YAML.write_text(content)

    def write_rc(self, enabled, interface):
        flags = f'-D -c {generate_rules.SURICATA_YAML}'
        if interface:
            flags += f' -i {interface}'
        content = (
            ('suricata_enable="YES"\n' if enabled else 'suricata_enable="NO"\n') +
            f'suricata_flags="{flags}"\n'
        )
        SURICATA_RC.parent.mkdir(parents=True, exist_ok=True)
        SURICATA_RC.write_text(content)

    def load_indproto_config(self):
        return generate_rules.load_config(None)

    def physical_interface(self, logical_iface):
        logical_iface = (logical_iface or "").strip()
        if not logical_iface or not CONFIG_XML.exists():
            return logical_iface
        try:
            root = ET.parse(CONFIG_XML).getroot()
            node = root.find(f"./interfaces/{logical_iface}/if")
            if node is not None and node.text:
                return node.text.strip()
        except Exception:
            pass
        return logical_iface

    def text(self, node, name, default=""):
        if node is None:
            return default
        found = node.find(name)
        if found is None or found.text is None:
            return default
        return found.text.strip()


class ServiceManager:
    def start(self):
        applied = ConfigManager().apply()
        result = self.run_service("onestart")
        if result["status"] == "error" and not self.is_running():
            return result
        return ok({"apply": applied, **self.status()}, "Suricata started")

    def stop(self):
        result = self.run_service("onestop")
        if result["status"] == "error" and self.is_running():
            return result
        return ok(self.status(), "Suricata stopped")

    def restart(self):
        applied = ConfigManager().apply()
        result = self.run_service("onerestart")
        if result["status"] == "error":
            result = self.run_service("onestart")
        if result["status"] == "error":
            return result
        return ok({"apply": applied, **self.status()}, "Suricata restarted")

    def status(self):
        result = subprocess.run(["/bin/pgrep", "-x", "suricata"], capture_output=True, text=True)
        pids = [int(item) for item in result.stdout.split() if item.isdigit()]
        state = "running" if pids else "stopped"
        return ok({
            "components": {"suricata": state},
            "capabilities": CapabilityProbe().probe(),
            "conflicts": ConflictDetector().detect(),
        }, "Suricata %s" % state)

    def run_service(self, action):
        command = ["/usr/sbin/service", "suricata", action]
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode == 0:
            return ok({"data": {"method": " ".join(command)}})
        return error((result.stderr or result.stdout or "Suricata service command failed").strip())

    def is_running(self):
        return subprocess.run(["/bin/pgrep", "-x", "suricata"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


class SuricataRuleBackend:
    def reload(self):
        applied = ConfigManager().apply()
        code = generate_rules.main()
        if code != 0:
            return error("industrial protocol rule generation failed")
        result = ok({
            "apply": applied,
            "capabilities": CapabilityProbe().probe(),
            "conflicts": ConflictDetector().detect(),
        }, "industrial protocol rules generated")
        return result


def ok(data=None, message="ok"):
    payload = {"status": "ok", "message": message}
    if data:
        payload.update(data)
    return payload


def error(message, data=None):
    payload = {"status": "error", "message": message}
    if data:
        payload.update(data)
    return payload


def query_logs(args):
    old_argv = sys.argv
    try:
        sys.argv = ["log_query.py"] + args
        return_code = log_query.main()
        if return_code not in (None, 0):
            return error("log query failed")
        return None
    finally:
        sys.argv = old_argv


def main(argv):
    action = argv[1] if len(argv) > 1 else "status"
    if action == "configure":
        return ConfigManager().apply()
    if action == "reload":
        return SuricataRuleBackend().reload()
    if action == "start":
        return ServiceManager().start()
    if action == "stop":
        return ServiceManager().stop()
    if action in ("restart_suricata", "restart"):
        return ServiceManager().restart()
    if action == "status":
        return ServiceManager().status()
    if action == "capabilities":
        return ok({
            "capabilities": CapabilityProbe().probe(),
            "conflicts": ConflictDetector().detect(),
        })
    if action == "log":
        logged = query_logs(argv[2:])
        return logged if logged is not None else None
    return error("unsupported action")


if __name__ == "__main__":
    result = main(sys.argv)
    if result is not None:
        print(json.dumps(result, separators=(",", ":")))
        sys.exit(1 if result.get("status") == "error" else 0)
